name: Build & Deploy to EC2 via GHCR

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # üîê Login GHCR (pour pull c√¥t√© EC2)
      - name: Login to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      # üê≥ Build & push frontend
      - name: Build & push frontend image
        env:
         VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: |
         docker build \
           --build-arg VITE_API_URL=$VITE_API_URL \
           -t ghcr.io/mbds-haiti/mini-projet-trio-react-frontend:latest \
           ./session01
         docker push ghcr.io/mbds-haiti/mini-projet-trio-react-frontend:latest



      # üöÄ Deploy on EC2
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/apps/mini-projet-trio-react
            git pull origin master
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
            cd ~/apps/mini-projet-trio-react
            docker compose pull
            docker compose down
            docker compose up -d
